services:
  fake-oidc-provider:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081" # for example service
  example:
    restart: unless-stopped
    network_mode: service:fake-oidc-provider
    build:
      context: example
      dockerfile: Dockerfile
    environment:
      - OIDC_ENDPOINT=http://localhost:8080
    depends_on:
      - fake-oidc-provider
